name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore MyWebApp.csproj

      - name: Build
        run: dotnet build MyWebApp.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test MyWebApp.csproj --no-build --configuration Release --verbosity normal
